# Generated by Django 5.2.8 on 2026-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartidores', '0002_alter_repartidor_id_alter_ubicacionrepartidor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ubicacionrepartidor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
