# Generated by Django 5.2.9 on 2026-04-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_alter_categoria_id_alter_producto_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='restaurantes.restaurante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurantes.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
