# Generated by Django 5.2.8 on 2026-04-23 19:50

import restaurantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_alter_categoria_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, help_text='PNG de exactamente 400×250 px con fondo transparente.', null=True, upload_to='restaurantes/', validators=[restaurantes.models.validar_png, restaurantes.models.validar_dimensiones_restaurante]),
        ),
    ]
