# Generated by Django 5.2.9 on 2026-04-28 17:36

import django.db.models.deletion
import restaurantes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_merge_20260427_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='logo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoias', to='restaurantes.restaurante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='restaurantes.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, help_text='PNG de exactamente 400×250 px con fondo transparente.', null=True, upload_to='restaurantes/', validators=[restaurantes.models.validar_png, restaurantes.models.validar_dimensiones_restaurante]),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
