# Generated by Django 5.2.9 on 2026-04-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_remove_producto_restaurante_remove_restaurante_logo_and_more'),
    ]

    operations = [
    ]