# Generated by Django 5.2.9 on 2026-04-28 19:35

import restaurantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_remove_producto_restaurante_remove_restaurante_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, help_text='PNG de exactamente 400×250 px con fondo transparente.', null=True, upload_to='restaurantes/', validators=[restaurantes.models.validar_png, restaurantes.models.validar_dimensiones_restaurante]),
        ),
    ]
