# Generated by Django 5.2.9 on 2026-04-28 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0007_alter_restaurante_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='restaurantes.restaurante'),
        ),
    ]
