# Generated by Django 6.0.3 on 2026-06-09 12:37

import cloudinary.models
import restaurantes.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0009_restaurante_imagen_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='PNG de exactamente 400×250 px con fondo transparente.', max_length=255, null=True, validators=[restaurantes.models.validar_png, restaurantes.models.validar_dimensiones_restaurante], verbose_name='image'),
        ),
    ]
