# Generated by Django 6.0.3 on 2026-04-29 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_detallepedido_id_alter_pedido_id'),
        ('usuarios', '0007_alter_calificacion_id_alter_codigorecuperacion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.direccion'),
        ),
    ]
