# Generated by Django 5.2.9 on 2026-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('repartidor', 'Repartidor'), ('restaurante', 'Restaurante')], default='cliente', max_length=20),
        ),
    ]
