# Generated by Django 5.2.8 on 2026-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_calificacion_id_alter_codigorecuperacion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
